.TH SLOG_Irec_IsEmpty 3 "8/11/1999" " " "SLOG_API"
.SH NAME
SLOG_Irec_IsEmpty \-  Check if the specified Interval record is empty 
.SH SYNOPSIS
.nf
int SLOG_Irec_IsEmpty( const SLOG_intvlrec_t *irec )
.fi
.SH UNMODIFIED INPUT VARIABLES 
.PD 0
.TP
.B irec 
- constant SLOG_intvlrec_t pointer to be checked
.PD 1

.SH MODIFIED OUTPUT VARIABLES 
.PD 0
.TP
.B returned value 
- integer return status
.PD 1

.SH USAGE NOTES ON THIS SUBROUTINE 
This routine is mainly used for debugging purposes.

.SH INCLUDE FILE NEEDED 
slog.h


.SH NOTES ON SLOG RETURN STATUS CODE 
There are 5 allowed SLOG returned status codes.  They include
SLOG_SUCCESS, SLOG_FAIL and SLOG_EOF.  Their actual values
are defined in slog.h

SLOG_SUCCESS is returned when no error is encountered.

SLOG_FAIL is returned when error is encounted.

SLOG_EOF is returned when End of file is encounted.

There are also SLOG_TRUE and SLOG_FALSE which are sued as boolean
values, in particular they are used in boolean functions which
are usually named as IsXXXXX(), AreXXXXX() and HasXXXXX().
.br


.SH LOCATION
../src/slog_irec_common.c
