.TH SLOG_SetIncreasingStarttimeOrder 3 "6/22/1999" " " "SLOG_API"
.SH NAME
SLOG_SetIncreasingStarttimeOrder \-  Set the flag for the interval records will be arranged in increasing starttime order.  That means there is NO second pass of the logfile and the starttime of the interval will be used to determine endtime of the frame. 
.SH SYNOPSIS
.nf
int SLOG_SetIncreasingStarttimeOrder( SLOG_STREAM  *slog )
.fi
.SH MODIFIED INPUT VARIABLES 
.PD 0
.TP
.B slog 
- pointer to SLOG_STREAM where interval records will be stored.
.PD 1

.SH MODIFIED OUTPUT VARIABLES 
.PD 0
.TP
.B returned value 
- integer return status.
.PD 1

.SH INCLUDE FILE NEEDED 
slog_header.h
.SH LOCATION
../src/slog_header.c
