.TH SLOG_PROF_SetExtraNumOfIntvlInfos 3 "8/7/1999" " " "SLOG_API"
.SH NAME
SLOG_PROF_SetExtraNumOfIntvlInfos \-  Write the starting file pointer  SLOG_prof_t to the slog's header and then set the maximum extra number of Interval  Description entries in Display Profile Table. 
.SH SYNOPSIS
.nf
int SLOG_PROF_SetExtraNumOfIntvlInfos(       SLOG_STREAM  *slog,
                                       const SLOG_uint32   Nentries_extra )
.fi
.SH MODIFIED INPUT VARIABLES 
.PD 0
.TP
.B slog 
- pointer to the SLOG_STREAM where SLOG Display Profile Table is
located.
.PD 1

.SH UNMODIFUED INPUT VARIABLES 
.PD 0
.TP
.B Nentries_extra 
- Number of extra interval description to be reserved
on the disk
.PD 1

.SH MODIFIED OUTPUT VARIABLES 
.PD 0
.TP
.B returned value 
- integer status code.
.PD 1

.SH USAGE NOTES ON THIS SUBROUTINE 


Notes on the Addition of Extra Record Definitions
This note is to clarify the usage of SLOG_RDEF_XXX() routines
especially while the user wants to add extra record definitions
to the logfile when the process of addition of interval records
to the logfile has been started, for instance if one needs to
add user marker interval records.

Under normal circumstances, the record definition table is created
by first opening the section of the logfile for storing the table
using SLOG_RDEF_Open().  Then add the record definition using
SLOG_RDEF_AddRecDef() and close the table section by
SLOG_RDEF_Close().

In the case that the logfile involves interval records whose
interval type are NOT known until the process of inserting
of the interval records to the logfile has been started, one
should open the SLOG_RDEF_Open().  Then add the known record
definitions using SLOG_RDEF_AddRecDef().  However, one should
NOT call SLOG_RDEF_Close() to close the table section.  Instead,
SLOG_RDEF_SetExtraNumOfRecDefs() should be called to set
the extra number of record definition entries needed( the
number can be greater than what one actually needs ).  Then
when user encounters a new interval record type,
SLOG_RDEF_AddExtraRecDef() can then be called to add the new
interval record type to the record definition table.  This
has to be done before adding the interval record to the logfile
using SLOG_Irec_ToOutputStream() which does NOT allow interval
record of with unknown interval type to the record definition
table.

.br



.SH INCLUDE FILE NEEDED 
slog_profile.h


.SH NOTES ON SLOG RETURN STATUS CODE 
There are 5 allowed SLOG returned status codes.  They include
SLOG_SUCCESS, SLOG_FAIL and SLOG_EOF.  Their actual values
are defined in slog.h

SLOG_SUCCESS is returned when no error is encountered.

SLOG_FAIL is returned when error is encounted.

SLOG_EOF is returned when End of file is encounted.

There are also SLOG_TRUE and SLOG_FALSE which are sued as boolean
values, in particular they are used in boolean functions which
are usually named as IsXXXXX(), AreXXXXX() and HasXXXXX().
.br


.SH LOCATION
../src/slog_profile.c
