.TH CLOG_newbuff 4 "11/29/1999" " " "MPE"
.SH NAME
CLOG_newbuff \-  get and initialize new block of buffer 
.SH SYNOPSIS
.nf
#include <stdio.h>
#include "mpe.h"
void CLOG_newbuff( CLOG_BLOCK **bufptr )
.fi
.SH INPUT PARAMETER

.PD 0
.TP
.B bufptr 
- pointer to be filled in with address of new block
.PD 1

.SH LOCATION
clog.c
